#!/bin/bash


git clone https://github.com/Kurento/kurento-tutorial-node.git
#cd kurento-tutorial-node/kurento-one2many-call
cd kurento-tutorial-node/kurento-hello-world
#cd kurento-tutorial-node/kurento-magic-mirror

git checkout 6.6.0
npm install

echo "Starting, looking for port ${KMS_PORT_8888_TCP_ADDR}"

npm start -- --ws_uri=ws://${KMS_PORT_8888_TCP_ADDR}:8888/kurento
